### ISSUE TITLE
ngx-swiper-wrapper

### ISSUE THREAD

**Issue by mgechev** [mgechev/ngcc-validation#123]
```
Debug: Invalid entry-point /Users/mgechev/Projects/ngcc-validation/ngx-swiper-wrapper-ngcc/node_modules/ngx-swiper-wrapper. It is missing required dependencies:
 - swiper/dist/js/swiper.js
```

**Comment by petebacondarwin** [comment]
This is because the import into `swiper` is a deep import - changing `import * as Swiper from 'swiper/dist/js/swiper.js';` to `import * as Swiper from 'swiper;` allows it to pass.

**Comment by petebacondarwin** [comment]
See https://github.com/zefoy/ngx-swiper-wrapper/issues/226 and https://github.com/angular/angular/issues/32097

**Comment by vugar005** [comment]
@petebacondarwin  I changed in ngx-swiper-wrapper.es5.js file
`import * as Swiper from 'swiper/dist/js/swiper.js';` to `import * as Swiper from 'swiper;` but error has not gone.

**Comment by JoostK** [comment]
This issue has been resolved in Angular's master branch.
