### ISSUE TITLE
Add ngrx

### ISSUE THREAD

**Issue by alan-agius4** [mgechev/ngcc-validation#175]

**Comment by mgechev** [comment]
Which is the missing ngrx package? Currently we have:

<img width="204" alt="Screen Shot 2019-08-12 at 11 28 40 PM" src="https://user-images.githubusercontent.com/455023/62919916-f5caef80-bd58-11e9-9f00-0af7659d1624.png">

**Comment by alan-agius4** [comment]
Oops
